apiVersion: v1
kind: PersistentVolume
metadata:
  name: airflow-pv-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/Users/apoorv.goswami/Github/gos-apoorv/apache-airflow/storage"  # Location of PV
