apiVersion: v1
kind: PersistentVolume
metadata:
  name: airflow-pv-dags
  labels:
    type: local
    storage-tier: dags
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "<local_path_for_dags>"  # Location of PV
