apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: airflow-pv-dag-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
  selector:
    matchLabels:
      storage-tier: dags
